fix NPE on open asRoot when lastSelectedNode is newly created
NullPointerException: Cannot invoke "String.equals(Object)" because "selectedNodeId" is null