fix NPE
java.lang.NullPointerException: Cannot invoke "org.freeplane.view.swing.map.NodeView.layoutOrientation()" because "parentView" is null
	at org.freeplane.view.swing.map.NodeView.getNextVisibleSibling(NodeView.java:580)
	at org.freeplane.view.swing.map.MapView.getNextVisibleSiblingAtAnyLevel(MapView.java:2121)
	at org.freeplane.view.swing.map.MapView.getNextVisibleSibling(MapView.java:1980)
	at org.freeplane.view.swing.map.MapView.suggestNewSelectedSibling(MapView.java:1973)
	at org.freeplane.view.swing.map.MapView.selectPreferredVisibleAncestorSibling(MapView.java:1928)
	at org.freeplane.view.swing.map.MapView.selectRelatedNode(MapView.java:1745)
	at org.freeplane.view.swing.map.MapView.selectRight(MapView.java:1735)